BMV2_SWITCH_EXE = simple_switch_grpc

#TOPO = TOPOLOGIAS/pod-topo/topology.json
#TOPO = TOPOLOGIAS/h1-s1-s2-h2/topology.json
#TOPO = TOPOLOGIAS/s1-h1-h2-h3-h4/topology.json
TOPO = TOPOLOGIAS/s1-h1-h2-s2-h3-h4/topology.json

include ../utils/Makefile
